EntityBundle\Entity\Place:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\PlaceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        category:
            type: string
            length: 255
        description:
            type: text
        address:
            type: string
            length: 255
        zipCode:
            type: integer
            length: 5
            column: zip_code
        city:
            type: string
            length: 255
        price:
            type: float
        distance:
            type: integer
        addDate:
            type: datetime
            column: add_date
        updateDate:
            type: datetime
            column: update_date
            nullable: true
        postName:
            type: string
            lenght: 255
            column: post_name
            nullable: true
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    manyToOne:
        user:
            targetEntity: EntityBundle\Entity\User
            inversedBy: user
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }