EntityBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        birthdate:
            type: date
        gender:
            type: string
            length: 1
        avatarName:
            type: string
            lenght: 255
            column: avatar_name
            nullable: true
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true

