fulltrip_review_delete:
    path:     /review/{id}/delete
    defaults: { _controller: FulltripBundle:Review:delete}

fulltrip_autocomplete:
    path:     /autocomplete
    defaults: { _controller: FulltripBundle:Search:autocomplete}

fulltrip_post_review:
    path:     /post/{id}/review
    defaults: { _controller: FulltripBundle:Review:post}

fulltrip_stay_get:
    path:     /stay/{user_id}
    defaults: { _controller: FulltripBundle:Stay:get }

fulltrip_stay_delete:
    path:     /post/{id}/stay-delete
    defaults: { _controller: FulltripBundle:Stay:delete }

fulltrip_stay_add:
    path:     /post/{id}/stay-add
    defaults: { _controller: FulltripBundle:Stay:add }

fulltrip_post_delete:
    path:     /post/{id}/delete
    defaults: { _controller: FulltripBundle:Post:delete }

fulltrip_post_edit:
    path:     /post/{id}/edit
    defaults: { _controller: FulltripBundle:Post:edit }

fulltrip_post_create:
    path:     /post/create
    defaults: { _controller: FulltripBundle:Post:create }

fulltrip_post:
    path:     /post/{id}
    defaults: { _controller: FulltripBundle:Post:show }

fulltrip_search:
    path:     /search
    defaults: { _controller: FulltripBundle:Search:index }

fulltrip_homepage:
    path:     /
    defaults: { _controller: FulltripBundle:Default:index }

fulltrip_dashboard:
    path:     /dashboard
    defaults: { _controller: FulltripBundle:Dashboard:index }

fulltrip_dashboard:
    path:     /dashboard
    defaults: { _controller: FulltripBundle:Dashboard:index }

fulltrip_dashboard_edit:
    path:   /dashboard/{id}/edit
    defaults: { _controller: FulltripBundle:Post:edit }

