fulltrip_post_delete:
    path:     /post/{id}/delete
    defaults: { _controller: FulltripBundle:Post:delete }

fulltrip_post_edit:
    path:     /post/{id}/edit
    defaults: { _controller: FulltripBundle:Post:edit }

fulltrip_post_create:
    path:     /post/create
    defaults: { _controller: FulltripBundle:Post:create }

fulltrip_post:
    path:     /post/{id}
    defaults: { _controller: FulltripBundle:Post:show }

fulltrip_search:
    path:     /search
    defaults: { _controller: FulltripBundle:Search:index }

fulltrip_homepage:
    path:     /
    defaults: { _controller: FulltripBundle:Default:index }